### ISSUE TITLE
Iterator helpers missing

### ISSUE THREAD

**Issue by dlindenkreuz** [facebook/hermes#1684]
## Bug Description

[Iterator Helpers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator#iterator_helper_methods) have been added to WebKit / JSC [recently](https://github.com/WebKit/WebKit/pull/34418). They are [available in Safari >= 18.4](https://webkit.org/blog/16574/webkit-features-in-safari-18-4/#javascript). Hermes does not support them yet.

I ran into this by accident because TypeScript's ECMA support already suggests helper methods on iterators.

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC
- [x] The issue is reproducible with the latest version of React Native.

Hermes git revision (if applicable): rn/0.79-stable
React Native version: 0.79
OS: macOS 14.7.2
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): arm64

## Steps To Reproduce

One-liner:
```js
new Map([["a", 1], ["b", 2]]).values().map(v => v * 2)
// Uncaught TypeError: new Map([["a", 1], ["b", 2]]).values().map is not a function (it is undefined)
```

## The Expected Behavior

Should not throw and instead return a new iterator. The code above works in Safari 18.4 console.

**Comment by avp** [comment]
Thanks for the report, we're working on implementing this feature.

**Comment by duraz0rz** [comment]
Yep, accidentally ran across this as well with `String.prototype.matchAll` and thought `matchAll` was missing at first, but it turns out, it's the `every`:

```
const placeholders = formula.matchAll(/{(.*?)}/g);
if (placeholders.every(([, key]) => key in context)) {
  // Do something
}
```

I guess, notably, `Iterator.prototype.every()` was made fully available in Node 22, so they're pretty new.

**Comment by ljharb** [comment]
Hermes (or users) can use https://npmjs.com/es-iterator-helpers to polyfill the feature prior to it being available at runtime.
